### ISSUE TITLE
issue with react 0.14.2

### ISSUE THREAD

**Issue by Bogdaan** [STRML/react-router-component-transition#10]
Now we have dependecy problem:
npm ERR! peerinvalid Peer react-dom@0.14.2 wants react@^0.14.2
npm ERR! peerinvalid Peer react-addons-test-utils@0.14.2 wants react@^0.14.2
npm ERR! peerinvalid Peer react-async@2.1.0 wants react@>=0.12.0 <0.14.0
npm ERR! peerinvalid Peer redbox-react@1.1.1 wants react@>=0.13.2 || ^0.14.0-rc1
npm ERR! peerinvalid Peer react-router-component@0.25.4 wants react@>=0.12.0 <0.14.0

It posible to support react 0.14.2?

**Comment by STRML** [comment]
Yeah, this just needs an update, the underlying RRC supports it just fine. I'll update the deps.

**Comment by Bogdaan** [comment]
:thumbsup: thanks
