### ISSUE TITLE
React 15 support

### ISSUE THREAD

**Issue by pankajpatel** [STRML/react-router-component-transition#12]
Is ReactJS 15 supported?

With react 15, when this package is installed, throws error:

```
├── UNMET PEER DEPENDENCY react@15.0.2
└── UNMET PEER DEPENDENCY react-addons-css-transition-group@15.0.2

npm WARN react-router-component-transition@0.2.0 requires a peer of react@^0.14.0 but none was installed.
npm WARN react-router-component-transition@0.2.0 requires a peer of react-addons-css-transition-group@^0.14.0 but none was installed.

```

**Comment by STRML** [comment]
This component is so small I usually just recommend copy/pasting it into your app so you have the freedom to edit it.

I don't have the time at the moment but dropping the peerDep versions to `*` seems appropriate.

**Comment by pankajpatel** [comment]
I would go ahead with copy the source in my repo for now.

But for `peerDep`, are you updating or I open a PR?
